# This file associates existing grooves with their time signature
# Marc Lashner

GROOVES = {
	('regular', (4, 4)): [
		'50srock',
		'60srock',
		'8beat',
		'arpeggio44',
		'ballad',
		'basicrock',
		'bebop',
		'beguine',
		'bigband',
		'bluegrass',
		'blues',
		'boneym',
		'bossanova',
		'broadway',
		'bubblerock',
		'bvfunk',
		'bwmarch',
		'calypso',
		'chacha',
		'charlseton',
		'countryblues',
		'countryswing',
		'descendingjazz',
		'desert',
		'dixie',
		'dixiemarch',
		'easyswing',
		'evansish',
		'folk',
		'folkballad',
		'folkrock',
		'folkyjazz',
		'foxtrot',
		'guitarballad',
		'hillcountry',
		'hymn',
		'jazzcombo',
		'jazzguitar',
		'jazzrhumba',
		'jazzrock',
		'jive',
		'lfusion',
		'lighttango',
		'lullaby',
		'mambo',
		'march',
		'mellowjazz',
		'merengue',
		'metronome',
		'modernjazz',
		'nitejazz',
		'pianoballad',
		'polka',
		'popballad',
		'popspiritual',
		'quickstep',
		'rb-ballad',
		'rb',
		'rhumba',
		'rockballad',
		'salsa',
		'samba',
		'showtune',
		'shuffleboggie',
		'ska',
		'softrock',
		'softshoe',
		'son',
		'spiritual',
		'stringballad',
		'strut',
		'swing',
		'tango',
		'trance',
		'twist',
		'westernswing',
		'zydeco',
		],
	('fast', (4, 4)): [
		'fastblues',
		'fastswing',
		],
	('slow', (4, 4)): [
		'slowblues',
		'slowbolero',
		'slowbroadway',
		'slowcountry',
		'slowjazz',
		'slowspiritual',
		],
	('regular', (3, 4)): [
		'arpeggiowaltz'
		'broadwaywalz',
		'countrywaltz',
		'jazzwaltz',
		'arpeggiowaltz',
		'frenchwaltz',
		'latinwaltz',
		'metronome3',
		'rockwaltz',
		'vienesewaltz',
		'waltz',
		],
	('fast', (3, 4)): [
		'fastjazzwaltz',
		'fastwaltz',
		],
	('regular', (6, 8)): [
		'68march',
		'68swing',
		'afro-cuban',
		'arpeggio68',
		'ballad68',
		'metronome6',
		'metronome68',
		],
	('regular', (12, 8)): [
		'ballad128',
		'blues128',
		'rock-128',
		],
	('regular', (12, 8)): [
		'jazz-54',
		],
	(None, None): [
		'none',
		],
}